name: MAIN_PULL_REQUEST

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    # needs: build
    steps:
      - name: Save PR number
        run: echo ${{ github.event.number }} > ./pr-id.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        env:
          cache-name: cache-nodemodules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install

      - name: Build 
        run: npm run build